# Welcome to kkomul's website!

# Site settings
title: kkomul
email: kkomul.com
description: > # this means to ignore newlines until "baseurl:"
  Dear Friends and family,
  My wife and I are very excited to share this wonderful news; WE ARE HAVE A BABY GIRL! 
  Baby girl (No name yet) is due in Auguest and I'll be posting her pictures on her website, kkomul.com.
  Later I will also list some possible names for the baby and I want you guys to vote on your favorite name.
  It will be fun for you guys and for us to pick the baby's name together.
  I can't believe this is really happening and I don't think the reality has hit me yet. 
  O.K guys stay tuned for more news and take care!
baseurl: "" # the subpath of your site, e.g. /blog
url: "kkomul.com" # the base hostname & protocol for your site
twitter_username: kkomul
github_username:  kkomul

# Build settings
markdown: kramdown
